config/routes.rb
CaptionWatch::Application.routes.draw do

  resources :companies

  resources :products

  resources :complaints
  root to: "home#index"
  get '/thanks', to: 'home#thanks'
  get '/stats', to: 'home#stats'

  

end

app/models/application_model.rb
class ApplicationModel < ActiveResource::Base

  def initialize(*params)
    self.site = "http://captionwatch-api.dev"
    self.user = "admin"
    super(*params)
  end

end

app/models/company.rb
class Company < ActiveResource::Base
    self.site = "http://captionwatch-api.dev"
    self.user = "admin"
end

app/models/complaint.rb
class Complaint < ActiveResource::Base
    self.site = "http://captionwatch-api.dev"
    self.user = "admin"
  # attr_accessor :url, :address, :custom_blurb
  # attr_reader :url, :address, :custom_blurb
end

app/models/product.rb
class Product < ActiveResource::Base
    self.site = "http://captionwatch-api.dev"
    self.user = "admin"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params[:company]
    end
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  def create
    # @company = Company.create(params)
    # @product = Product.create(params)
    params[:complaint][:product_id]=1
    @complaint = Complaint.new(params)

    if @complaint.save
      session[:complaint_id]= @complaint.id
      redirect_to '/thanks'
    end
  end

  def index
    @company = Company.new(name: '')
    @product = Product.new(name: '')
    @complaint = Complaint.new(url: '')
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def thanks
    @complaint = Complaint.find(session[:complaint_id])
    # session[:complaint_id]= nil
  end

  def stats
    @complaints = Complaint.all.size
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params[:product]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/companies/_form.html.haml
= simple_form_for(@company) do |f|
  = f.error_notification

  .inputs

  .actions
    = f.button :submit

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
%h1 Listing companies

%table
  %tr
    %th
    %th
    %th

  - @companies.each do |company|
    %tr
      %td= link_to 'Show', company
      %td= link_to 'Edit', edit_company_path(company)
      %td= link_to 'Destroy', company, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Company', new_company_path

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_company_path(@company)
\|
= link_to 'Back', companies_path

app/views/complaints/_form.html.haml
= simple_form_for(@complaint) do |f|
  = f.error_notification

  .inputs

  .actions
    = f.button :submit

app/views/complaints/create.html.haml
%h1 Complaints#create
%p Find me in app/views/complaints/create.html.haml

app/views/complaints/edit.html.haml
%h1 Editing complaint

= render 'form'

= link_to 'Show', @complaint
\|
= link_to 'Back', complaints_path

app/views/complaints/index.html.haml
%h1 Complaints#index
%p Find me in app/views/complaints/index.html.haml

app/views/complaints/new.html.haml
%h1 New complaint

= render 'form'

= link_to 'Back', complaints_path

app/views/complaints/show.html.haml
%h1 Complaints#show
%p Find me in app/views/complaints/show.html.haml

app/views/home/index.html.haml
.row
  .large-12.columns
    .hero
      %h1 Accessiblity is not a dirty word. Tell Congress!
      .large-10.columns.large-centered
        %p The state of captioning accessibilty on various media platforms is dismal. We demand that the US Congress execute legislation outlining clear accessibility requirements to support all Americans.
        %a.button.large
          Watch Video

        / %iframe{:allowfullscreen => "1", showinfo: "0", :frameborder => "0", :height => "480", :src => "//www.youtube-nocookie.com/embed/EgSrZ-s3MTY?rel=0", :width => "853"}
.row
  .letter
    .large-12.columns
      #send-letter
        %h2 Send to Congress
        = simple_form_for Complaint.new do |f|
          .large-6.columns
            = fields_for Company.new do |c|
              .fieldbox
                .panel
                  = c.label :name, "Company Name"
                  = c.text_field :name, value: "Netflix"

            = fields_for Product.new do |p|
              .fieldbox
                .panel
                  = p.label :name, "Product Name"
                  = p.text_field :name, value: "House of Cards"
              .fieldbox
                .panel
                  = f.label :url, "Problem url"
                  .row.collapse
                    .small-3.large-2.columns
                      %span.prefix http://
                    .small-9.large-10.columns
                      = f.text_field :url, placeholder: "Enter ur url yo", value: "http://netflix.com/houseofcards"
              .fieldbox
                .panel
                  = f.label :address, "Your address"
                  = f.text_field :address, value: "222 Clearwood Ave Riverside CA"
              .fieldbox
                .panel
                  = f.label :email, "Your email"
                  = f.text_field :email, value: "john@johndoe.com"

          .large-6.columns.compliant
            .fieldbox
              .panel
                = f.label :custom_blurb, "Letter <span><a class='button small'>ASL</a></span>".html_safe
                = f.text_area :custom_blurb, class: "blurb", value: "oh my god this works!", placeholder: "The Washington Post and the Guardian recently published reports based on information provided by an intelligence contractor showing how the NSA and the FBI are gaining broad access to data collected by nine of the leading U.S. Internet companies and sharing this information with foreign governments. As reported, the U.S. government is extracting audio, video, photographs, e-mails, documents, and connection logs that enable analysts to track a person's movements and contacts over time. As a result, the contents of communications of people both abroad and in the U.S. can be swept in without any suspicion of crime or association with a terrorist organization."
            .send
              = f.submit "Send Letter", class: "button expand large"

app/views/home/stats.html.haml
.row
  .large-12.columns
    .large-4.columns
      .panel
        %h3 Total Complaints
        %h1= @complaints

app/views/home/thanks.html.haml
.row
  .large-12.columns
    %h1 Thank you.
    .large-8.columns.large-centered
      %h3 We will deliver an email on your behalf to Congress as part of our call for improvement of accessiblity.
.row
  .large-6.columns
    .panel
      %h3 Your letter
      %h4 To:
      %p
        = @complaint.blurb

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/ [if (gte IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "CaptionWatch"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tags
  %body
    .row
      .large-12.columns
        %nav.top-bar
          %ul.title-area
            / Title Area
            %li.name
              %h1
                %a{:href => "/"}
                  CaptionWatch
            %li.toggle-topbar.menu-icon
              %a{:href => "#"}
                %span menu
          %section.top-bar-section
            / Right Nav Section
            %ul.right
              %li
                %a{:href => "/about"} ABOUT
              %li
                %a{:href => "/stats"} STATS
    = yield
    = javascript_include_tag "application"
    %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js", :type => "text/javascript"}
    %script{:src => "//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js", :type => "text/javascript"}

app/views/products/_form.html.haml
= simple_form_for(@product) do |f|
  = f.error_notification

  .inputs

  .actions
    = f.button :submit

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

%table
  %tr
    %th
    %th
    %th

  - @products.each do |product|
    %tr
      %td= link_to 'Show', product
      %td= link_to 'Edit', edit_product_path(product)
      %td= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path